name: Preflight
on:
    push:
    workflow_dispatch:

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v1
              with:
                egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

            - name: Source checkout
              uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v2

            - name: Setup node
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v2.5.1
              with:
                  node-version: 16
                  cache: 'yarn'

            - name: Check version
              run: yarn --version

            - name: Install deps
              run: yarn

            - name: Install pkg
              run: yarn add pkg

            - name: Check outdated
              run: yarn outdated

            - name: Build binary
              run: yarn pkg .

